version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '25432:5432'

volumes:
  db:
