# docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '25432:5432'

volumes:
  db:
